title: Board
author: Thanh Lai
url: http://thanhlai.com/board
description: "Research, links, technical materials and journals."

permalink: /:title/
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM

exclude:
 - README.md
 - CNAME
 
gems:
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
